# fly.toml app configuration file generated for speeding-hsl-busses on 2025-12-31T10:28:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'speeding-hsl-busses'
primary_region = 'arn'

[build]

[processes]
  app = "node dist/index.js"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[mounts]]
  source = "data"
  destination = "/data"
  initial_size = 1
